### ISSUE TITLE
CapsuleControllerDesc/BoxControllerDesc generated with incorrect padding

### ISSUE THREAD

**Issue by wrapperup** [tgolsson/physx-odin#4]
Currently, the bindgen creates this struct for `PxCapsuleControllerDesc`

```odin
CapsuleControllerDesc :: struct {
    using _: ControllerDesc,
    radius: _c.float,
    height: _c.float,
    climbingMode: CapsuleClimbingMode,
    _pad26: [4]u8,
}
```
However, the C++ struct itself adds another virtual method, which doesn't seem to get picked up. Is it assuming that all virtual methods in deeper structs are overriding? The generated struct should be like this:
```odin
CapsuleControllerDesc :: struct {
    using _: ControllerDesc,
    _pad: [4]u8, // missing padding
    radius: _c.float,
    height: _c.float,
    climbingMode: CapsuleClimbingMode,
    _pad26: [4]u8,
}
```

**Comment by tgolsson** [comment]
Thanks for the report! Is this on Windows or Linux? Compiler version?

There is no such assumption about virtuals, but *at least one* of these ControllerDesc structs ended up in a weird situation of a derived class having a *negative* offset relative to where you would expect it with regular C rules. These are non-POD data so there are no rules on the layout. 

The specific issue occurs if the base class ends up being padded with 4 bytes, virtual, and then the derived class has a 4-byte field at the start (which looks suspiciously like what you've posted). I observed this with Clang-15 on Linux. This is fine under C++ object rules since those bytes aren't addressable (through the base-class) without invoking UB. I'm guessing this is on Windows?

**Comment by tgolsson** [comment]
As an aside, this looks like a test issue as well, we have auto-generated tests for layouts. I haven't had time to set up any CI, so it's likely that I've only properly tested Linux. (Assuming my previous guess is right...)

**Comment by wrapperup** [comment]
Thanks!
